#include <io/tty.h>
#include <device/keyboard.h>

/**
 * German (de_DE) keyboard layout (ISO 9995-1) translation table
 * for ASCII (ISO 8859-1) characters.
 */
tty_keyboard_layout_t tty_keyboard_layout_de_DE = {
    .name = "de_DE",
    .keymap = (tty_keymap_entry_t[]) {
        {KEYBOARD_KEYCODE_GRAVE, '^', '°'},
        {KEYBOARD_KEYCODE_1, '1', '!'},
        {KEYBOARD_KEYCODE_2, '2', '"'},
        {KEYBOARD_KEYCODE_3, '3', '§'},
        {KEYBOARD_KEYCODE_4, '4', '$'},
        {KEYBOARD_KEYCODE_5, '5', '%'},
        {KEYBOARD_KEYCODE_6, '6', '&'},
        {KEYBOARD_KEYCODE_7, '7', '/'},
        {KEYBOARD_KEYCODE_8, '8', '('},
        {KEYBOARD_KEYCODE_9, '9', ')'},
        {KEYBOARD_KEYCODE_0, '0', '='},
        {KEYBOARD_KEYCODE_MINUS, 'ß', '?'},
        {KEYBOARD_KEYCODE_EQUAL, '`', '`'},
        {KEYBOARD_KEYCODE_BACKSPACE, '\b', '\b'},
        {KEYBOARD_KEYCODE_TAB, '\t', '\t'},
        {KEYBOARD_KEYCODE_Q, 'q', 'Q'},
        {KEYBOARD_KEYCODE_W, 'w', 'W'},
        {KEYBOARD_KEYCODE_E, 'e', 'E'},
        {KEYBOARD_KEYCODE_R, 'r', 'R'},
        {KEYBOARD_KEYCODE_T, 't', 'T'},
        {KEYBOARD_KEYCODE_Y, 'z', 'Z'},
        {KEYBOARD_KEYCODE_U, 'u', 'U'},
        {KEYBOARD_KEYCODE_I, 'i', 'I'},
        {KEYBOARD_KEYCODE_O, 'o', 'O'},
        {KEYBOARD_KEYCODE_P, 'p', 'P'},
        {KEYBOARD_KEYCODE_LEFT_BRACKET, 'ü', 'Ü'},
        {KEYBOARD_KEYCODE_RIGHT_BRACKET, '+', '*'},
        {KEYBOARD_KEYCODE_ENTER, '\n', '\n'},
        {KEYBOARD_KEYCODE_A, 'a', 'A'},
        {KEYBOARD_KEYCODE_S, 's', 'S'},
        {KEYBOARD_KEYCODE_D, 'd', 'D'},
        {KEYBOARD_KEYCODE_F, 'f', 'F'},
        {KEYBOARD_KEYCODE_G, 'g', 'G'},
        {KEYBOARD_KEYCODE_H, 'h', 'H'},
        {KEYBOARD_KEYCODE_J, 'j', 'J'},
        {KEYBOARD_KEYCODE_K, 'k', 'K'},
        {KEYBOARD_KEYCODE_L, 'l', 'L'},
        {KEYBOARD_KEYCODE_SEMICOLON, 'ö', 'Ö'},
        {KEYBOARD_KEYCODE_APOSTROPHE, 'ä', 'Ä'},
        {KEYBOARD_KEYCODE_BACKSLASH, '#', '\''},
        {KEYBOARD_KEYCODE_LEFT_SHIFT, '\0', '\0'},
        {KEYBOARD_KEYCODE_Z, 'y', 'Y'},
        {KEYBOARD_KEYCODE_X, 'x', 'X'},
        {KEYBOARD_KEYCODE_C, 'c', 'C'},
        {KEYBOARD_KEYCODE_V, 'v', 'V'},
        {KEYBOARD_KEYCODE_B, 'b', 'B'},
        {KEYBOARD_KEYCODE_N, 'n', 'N'},
        {KEYBOARD_KEYCODE_M, 'm', 'M'},
        {KEYBOARD_KEYCODE_COMMA, ',', ';'},
        {KEYBOARD_KEYCODE_PERIOD, '.', ':'},
        {KEYBOARD_KEYCODE_SLASH, '-', '_'},
        {KEYBOARD_KEYCODE_SPACE, ' ', ' '},
    },
    .keymap_size = 52
};
