#!/usr/bin/env make

.PHONY: all clean

ROOTDIR ?= $(realpath ..)

# The abi subproject consists of headers only. Both targets exist so that it
# can be driven like the other subprojects, there is simply nothing to build
# and nothing to remove.

all:

clean:
